create table _user(
    id int generated by default as identity primary key,
    login text not null unique,
    password text not null
);

create table product_metadata (
    product_id int primary key,
    self_cost double precision not null,
    weight double precision,
    damping_cost int,
    min_profit_percent double precision,
    amount int,
    seller_id int references _user(id)
);

create table market (
    market_id text primary key,
    phone_number text not null,
    is_enable bool
);