create table _user(
                      id int generated by default as identity primary key,
                      login text not null unique,
                      password text not null
);

create table market (
                        id int generated by default as identity primary key,
                        market_id text,
                        phone_number text not null,
                        is_enable bool,
                        user_id int references _user(id),
                        login text not null,
                        password text not null
);

create table product_metadata (
                                  id int generated by default as identity primary key,
                                  product_id text not null ,
                                  self_cost double precision not null,
                                  weight double precision,
                                  damping_cost int,
                                  min_profit_percent double precision,
                                  amount int,
                                  market_id int
);